### ISSUE TITLE
Growl support

### ISSUE THREAD

**Issue by plumlee** [magnars/autolint#1]
Docs say 'Make sure you also install the growlnotify in the Extras-folder.', but there's no Extras folder. Installed growl using npm, and the tests run w/o error, but Growl doesn't notify. What am I missing?

Sorry, just figured this out. Wasn't clear that growlnotify was part of Growl, not autolint.

**Comment by magnars** [comment]
Hey Scott, thanks for trying autolint. The program works fine without growlnotify installed (there just isn't any notifications), so that's probably what you're seeing.

If you install Growl from http://growl.info/ there's an Extras-folder with growlnotify in it. This is the program that node-growl is using to talk to Growl.

Does that help at all?

**Comment by plumlee** [comment]
Yeah, I'm an idiot. Figured that out an hour after I posted. Sorry.

**Comment by plumlee** [comment]
One more question. It's not clear to mr where the .JSON file should live. Root of my home, root of autonomy, elsewhere?

**Comment by magnars** [comment]
No problem. :-) `autolint` looks for `autolint.json` in the current directory, so I usually place it in the root of the project. But where ever you want to run the command from is fine.

Hope it serves you well!
